server:
  port: 9091
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mzzb_spider_dev?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: mzzb_spider_dev
    password: mzzb_spider_dev
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL57Dialect
      hibernate.format_sql: true
    show-sql: true

logging:
  level:
    cdp4j.flow: WARN

---
spring:
  profiles: pro
  datasource:
    url: jdbc:mysql://localhost:3306/mzzb_spider_pro?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: mzzb_spider_pro
    password: mzzb_spider_pro
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false